Repository instill-ai/model, pull requests merged in 2023-09, with the labels that each got.

#30 ci(workflow): create workflow to automate test make latest and all
  .github/workflows/make-all.yml
  .github/workflows/make-latest.yml
Labels: ⚗️ instill-model

#31 docs(LICENSE,README): make content up-to-date
  LICENSE
  README.md
Labels: ⚗️ instill-model

#34 docs(contributing): move contributing to dedicated file
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/SECURITY.md
  README.md
Labels: ⚗️ instill-model

#21 ci(workflow): add integration-test-latest|release workflow for mac
  .github/workflows/helm-integration-test-backend.yml
  .github/workflows/integration-test-backend.yml
  .github/workflows/integration-test-release.yml
Labels: ⚗️ instill-model, instill model

#36 ci(Makefile): fix make stop and start
  Makefile
  docker-compose.yml
Labels: instill model

#35 chore(model): create horizontal pod autoscaling
  charts/model/templates/controller-model/hpa.yml
  charts/model/templates/model-backend/hpa.yml
  charts/model/templates/triton/hpa.yml
  charts/model/values.yaml
Labels: ⚗️ instill-model
